### ISSUE TITLE
fga tool documentation correction

### ISSUE THREAD

**Issue by poe4** [lasseignelab/CINmetrics#1]
Thank you for creating this package! One small correction to the documentation for the cnvData argument dataframe description. This should read: "dataframe containing following columns: Sample, **_Chromosome,_** Start, End, Num_Probes, Segment_Mean."

Chromosome column is missing in the current documentation, which returns 0 across the board when the fga() function is run.

Thank you!

**Comment by vishaloza** [comment]
Hello, Thank you for using the package and providing the feedback. We have addressed the issue along with other changes. Will soon update it on CRAN
