### ISSUE TITLE
How to apply this on single cell data ?

### ISSUE THREAD

**Issue by Krithika-Bhuvan** [lasseignelab/CINmetrics#2]
Hello , I'm looking to apply this package to run CINmetrics on single cell data. I have completed  segmentation using "EpiAneufinder" package , and have an CNV output file that is like this:
* Rows are segements
* Columns are cell ids. 
* Data values: 0 means loss, 1 means normal, and 2 means gain.

<img width="383" alt="image" src="https://github.com/user-attachments/assets/8143f7bd-8aed-43cb-87a2-80d74e299edf">

Questions
* If I CINmetrics on this data and get instability metrics, would i be able to group each cell into either "malignant" (aka tumor or aneuploid) or "non-maligment" (aka tumor or diploid) to each cell. ?
* Can you advice what settings to use when running CINmetrics on this data ?

Thanks, K

**Comment by blasseigne** [comment]
Hi @Krithika-Bhuvan, Thank you for your interest in our tool. Unfortunately, it wasn't developed for or tested with single-cell data, so I can't recommend that approach without substantial testing.

**Comment by Krithika-Bhuvan** [comment]
Thanks for the information
